version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webgolang
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: webgolang
    ports:
      - "9090:8080"

volumes:
  db-data:





